server:
  port: 5000

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://doitcommit.cpf2it5tykya.ap-northeast-2.rds.amazonaws.com:3306/do_it_commit?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: doitcommit11
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/doitcommit
  #    username: sa
  #    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
    open-in-view: false
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 453703790848-lj72r35it9k1jg2e3ip97ti9u5k6tn8c.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:5000/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            client-id: Iv1.8767b31cd9c5786c
            client-secret: 9e80c1a56f100cc9fd7e5531b898e8b92a29d7cf
            redirect-uri: http://localhost:5000/login/oauth2/code/github
            scope:
              - read:user


app:
  token:
    secretKey: 1234rhjknsdkjn2kKJnfkjanhdsfkjsdnaflkasjfnksjdfnksjdfs478415616
  oauth2:
    authorized-redirect-url: http://localhost:3000

file:
  path: D:\doitcommit\upload\

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true