server:
  port: 5000

spring:
#  main:
#    allow-bean-definition-overriding: true
#    datasource:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://do-it-commit-db.database.windows.net:1433;database=do-it-commit
#      username: do-it-commit-admin
#      password: Dndltzjalt*
  datasource:
    url: jdbc:h2:tcp://localhost/~/doitcommit
    username: sa
    driver-class-name: org.h2.Driver

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
    open-in-view: false
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://apis.doit-commit.kro.kr/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://apis.doit-commit.kro.kr/login/oauth2/code/github
            scope:
              - read:user


app:
  token:
    secretKey: 1234rhjknsdkjn2kKJnfkjanhdsfkjsdnaflkasjfnksjdfnksjdfs478415616
  oauth2:
    authorized-redirect-url: https://www.doit-commit.kro.kr





