server:
  port: 5000

spring:
  main:
     allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: admin
    password: ${DATABASE_PASSWORD}
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/doitcommit
#    username: sa
#    driver-class-name: org.h2.Driver

  redis:
    host: ${REDIS_SERVER}
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
    open-in-view: false
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://apis.doit-commit.kro.kr/login/oauth2/code/google
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: https://apis.doit-commit.kro.kr/login/oauth2/code/github
            scope:
              - read:user

app:
  token:
    secretKey: ${JWT_SECRET_KEY}
  oauth2:
    authorized-redirect-url: https://www.doit-commit.kro.kr

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

file:
  path: D:\doitcommit\upload\

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true


