name: do-it-commit

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 11

        - name: Grant execute permission for gradlew
          run: chmod +x ./gradlew
          shell: bash

        - name: Build with Gradle
          run: ./gradlew clean build
          shell: bash

        - name: Get current time
          uses: 1466587594/get-current-time@v2
          id: current-time
          with:
            format: YYYY-MM-DDTHH-mm-ss
            utcOffset: "+09:00"

        - name : Generate deployment package
          run: zip -r deploy.zip .

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

        - name: Read secrets from AWS Secrets Manager into environment variables
          uses: abhilash1in/aws-secrets-manager-action@v1.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2
            secrets: |
              /secret/do-it-commit2
            parse-json: false

        - name : Deploy to EB
          uses: einaregilsson/beanstalk-deploy@v14
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: do-it-commit
            environment_name: Doitcommit-env
            version_label: "java-${{steps.current-time.outputs.formattedTime}}"
            region: ap-northeast-2
            deployment_package: deploy.zip